version: "3"
services:
  frontend:
    container_name: dbs_next
    restart: always
    build: frontend
    ports:
      - "5001:3000"
    links:
      - backend
  backend:
    container_name: dbs_node
    restart: always
    build: backend
    ports:
      - "5000:5000"
    links:
      - mongo
  mongo:
    container_name: dbs_mongo
    image: mongo
    ports:
      - "27017:27017"
