version: "3"
services:
  frontend:
    container_name: dbs_next
    restart: always
    build: frontend
    ports:
      - "5001:3000"
    links:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
  backend:
    container_name: dbs_node
    restart: always
    build: backend
    ports:
      - "5000:5000"
      - "9229:9229"
    volumes:
      - ./backend:/app
